### ISSUE TITLE
电路与模拟电子基础似乎没了

### ISSUE THREAD

**Issue by ACce1er4t0r** [FengGuanxi/HDU-Experience#4]
电路与模拟电子基础似乎没了

**Comment by ACce1er4t0r** [comment]
不对，是直接点开的连接是
https://github.com/FengGuanxi/HDU-Experience/blob/master/%E5%AD%A6%E4%B9%A0/%E7%94%B5%E8%B7%AF%E4%B8%8E%E6%A8%A1%E6%8B%9F%E7%94%B5%E5%AD%90%E5%9F%BA%E7%A1%80
但是把blob换成tree就能看见。。。。

**Comment by FengGuanxi** [comment]
我一般发给别人的都是主页链接的啊，为什么会出现这种情况…

**Comment by FengGuanxi** [comment]
如果没什么问题，那我关闭这个issue了
